### ISSUE TITLE
Creating a new profile always requires an expiration date

### ISSUE THREAD

**Issue by benjxia** [cse110-fa22-group25/warrantracker#30]
Expected behavior: No error when attempting to create a profile without an expiration date.

**Comment by benjxia** [comment]
where was this fixed

**Comment by benjxia** [comment]
or are we leaving as is

**Comment by karthikv6** [comment]
I was looking into it and when I tried I was forced to add an expiration date when creating a new profile, I think it is enforced at line 172 of index.html

**Comment by benjxia** [comment]
"not a bug, it's a feature"
