### ISSUE TITLE
search_tag() bugs

### ISSUE THREAD

**Issue by chrisliang12** [cse110-fa22-group25/warrantracker#40]
search_tag() is not working as desired. It cannot give tag recommendations based on user input correctly.

I will fix this when implementing the search feature.

**Comment by chrisliang12** [comment]
The bug has been fixed in branch "32-searching-for-profiles".

**Comment by benjxia** [comment]
bro dont implement an entire multiway trie for this

**Comment by chrisliang12** [comment]
> bro dont implement an entire trie for this

What do you mean?

**Comment by benjxia** [comment]
thought you were going to implement a whole autocomplete system

**Comment by chrisliang12** [comment]
No, the bug was the search_tag did not compare the user input at all. I
just edited a few lines to fix it.

**Comment by chrisliang12** [comment]
The bug has been fixed in branch "32-searching-for-profiles".
