### ISSUE TITLE
The first great refactor

### ISSUE THREAD

**Issue by benjxia** [cse110-fa22-group25/warrantracker#9]
we should probably edit the html to use less divs later

_Originally posted by @benjxia in https://github.com/cse110-fa22-group25/warrantracker/issues/8#issuecomment-1305306365_

**Comment by chrisliang12** [comment]
Sure, I will do some code refactoring today or tomorrow. For now, I just assemble the whole HTML with default bootstrap components.

**Comment by benjxia** [comment]
Need to add types to JSDoc comments
